### ISSUE TITLE
Open 5D chess discord invite

### ISSUE THREAD

**Issue by Alexbay218** [Jett59/5d-chess#1]
Not sure if your project looks to implement "5D Chess with Multiverse Time Travel". If not, you can just ignore this.

I'm the lead developer of https://chessin5d.net and I'm looking to gather people interested in creating open source projects around 5D chess. Here is the discord link: https://discord.chessin5d.net

There are 5+ different developers on there working on their own projects, so feel free to drop in and say hi.

**Comment by Jett59** [comment]
Hello,
Thank you for noticing this project and mentioning this group. I will consider this and (depending on various factors) may join at some point in the future.
Good luck with your 5d chess project. Hope it goes well.
